version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  apt_packages:
    - graphviz
  jobs:
    post_install:
      - pip install poetry~=1.5.1
      - poetry config virtualenvs.create false
      - pip install -r requirements.txt